### ISSUE TITLE
I fucked up

### ISSUE THREAD

**Issue by acheong08** [nlpodyssey/spago#120]
```go
--- FAIL: TestResults (0.02s)
panic: runtime error: makeslice: len out of range [recovered]
        panic: runtime error: makeslice: len out of range [recovered]
        panic: runtime error: makeslice: len out of range [recovered]
        panic: runtime error: makeslice: len out of range [recovered]
        panic: runtime error: makeslice: len out of range [recovered]
        panic: runtime error: makeslice: len out of range

goroutine 24 [running]:
testing.tRunner.func1.2({0xb61d80, 0xd37030})
        /usr/local/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1529 +0x39f
panic({0xb61d80, 0xd37030})
        /usr/local/go/src/runtime/panic.go:884 +0x213
encoding/gob.catchError(0xc0001861f0)
        /usr/local/go/src/encoding/gob/error.go:38 +0x6d
panic({0xb61d80, 0xd37030})
        /usr/local/go/src/runtime/panic.go:884 +0x213
encoding/gob.catchError(0xc0001861f0)
        /usr/local/go/src/encoding/gob/error.go:38 +0x6d
panic({0xb61d80, 0xd37030})
        /usr/local/go/src/runtime/panic.go:884 +0x213
encoding/gob.catchError(0xc000186270)
        /usr/local/go/src/encoding/gob/error.go:38 +0x6d
panic({0xb61d80, 0xd37030})
        /usr/local/go/src/runtime/panic.go:884 +0x213
encoding/gob.catchError(0xc000186270)
        /usr/local/go/src/encoding/gob/error.go:38 +0x6d
panic({0xb61d80, 0xd37030})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/nlpodyssey/spago/mat.(*Dense[...]).unmarshalBinaryFloat32(0xd4de80, {0xc00003c709, 0x611, 0x614})
        /home/acheong/go/pkg/mod/github.com/nlpodyssey/spago@v1.0.2-0.20230425104021-8a128747fb24/mat/dense_marshaling.go:91 +0xee
github.com/nlpodyssey/spago/mat.(*Dense[...]).UnmarshalBinary(0xd4de80?, {0xc00003c709, 0xc32ea0?, 0xc00006f400?})
        /home/acheong/go/pkg/mod/github.com/nlpodyssey/spago@v1.0.2-0.20230425104021-8a128747fb24/mat/dense_marshaling.go:41 +0x53
encoding/gob.(*Decoder).decodeGobDecoder(0xbf5e40?, 0xc000153100, 0xc000164e20, {0xc32ea0?, 0xc0001241e0?, 0x7fdf639685b8?})
        /usr/local/go/src/encoding/gob/decode.go:775 +0x1b6
encoding/gob.(*Decoder).gobDecodeOpFor.func1(0xb?, 0xc000164e20?, {0xbf5e40?, 0xc0001241e0?, 0x196?})
        /usr/local/go/src/encoding/gob/decode.go:1004 +0xc5
encoding/gob.(*Decoder).decodeSingle(0xc32ea0?, 0xc000164ee0, {0xbf5e40?, 0xc0001241e0?, 0x7fdf39370788?})
        /usr/local/go/src/encoding/gob/decode.go:461 +0x19b
encoding/gob.(*Decoder).decodeValue(0xc000186200, 0xc32ea0?, {0xc32ea0?, 0xc0002067f0?, 0x0?})
        /usr/local/go/src/encoding/gob/decode.go:1251 +0x277
encoding/gob.(*Decoder).decodeInterface(0xc000186200, {0xd48fa8?, 0xc28440}, 0xc000164e00, {0xc28440?, 0xc00396b6e0?, 0x0?})
        /usr/local/go/src/encoding/gob/decode.go:718 +0x265
encoding/gob.(*Decoder).decOpFor.func5(0xb97d60?, 0xc00396b6e0?, {0xc28440?, 0xc00396b6e0?, 0x0?})
        /usr/local/go/src/encoding/gob/decode.go:903 +0x45
encoding/gob.(*Decoder).decodeStruct(0xb594c0?, 0xc000164e80, {0xb97d60?, 0xc00396b6e0?, 0xd38560?})
        /usr/local/go/src/encoding/gob/decode.go:494 +0x18b
encoding/gob.(*Decoder).decodeValue(0xc000186200, 0x451200?, {0xb0e600?, 0xc00396b6e0?, 0xc0001a5a01?})
        /usr/local/go/src/encoding/gob/decode.go:1249 +0x24e
encoding/gob.(*Decoder).DecodeValue(0xc000186200, {0xb0e600?, 0xc00396b6e0?, 0x0?})
        /usr/local/go/src/encoding/gob/decoder.go:229 +0x1b7
encoding/gob.(*Decoder).Decode(0xc000186200, {0xb0e600?, 0xc00396b6e0?})
        /usr/local/go/src/encoding/gob/decoder.go:204 +0x165
github.com/nlpodyssey/spago/nn.(*BaseParam).UnmarshalBinary(0xc000124190, {0xc004e00009, 0x6bc, 0x4891da})
        /home/acheong/go/pkg/mod/github.com/nlpodyssey/spago@v1.0.2-0.20230425104021-8a128747fb24/nn/baseparam_marshaling.go:46 +0xbf
encoding/gob.(*Decoder).decodeGobDecoder(0xc32040?, 0xc000153180, 0xc000164c20, {0xc32760?, 0xc000124190?, 0x7fdf639685b8?})
        /usr/local/go/src/encoding/gob/decode.go:775 +0x1b6
encoding/gob.(*Decoder).gobDecodeOpFor.func1(0xb?, 0xc000164c20?, {0xc32040?, 0xc000124190?, 0x196?})
        /usr/local/go/src/encoding/gob/decode.go:1004 +0xc5
encoding/gob.(*Decoder).decodeSingle(0xc32760?, 0xc000164cc0, {0xc32040?, 0xc000124190?, 0x7fdf39370788?})
        /usr/local/go/src/encoding/gob/decode.go:461 +0x19b
encoding/gob.(*Decoder).decodeValue(0xc000186180, 0xc32760?, {0xc32760?, 0xc000206698?, 0xc0002dd810?})
        /usr/local/go/src/encoding/gob/decode.go:1251 +0x277
encoding/gob.(*Decoder).decodeInterface(0xc000186180, {0xd48fa8?, 0xbd02c0}, 0xc000164c00, {0xbd02c0?, 0xc0001a59e0?, 0xc00257b388?})
        /usr/local/go/src/encoding/gob/decode.go:718 +0x265
encoding/gob.(*Decoder).decOpFor.func5(0xbda6c0?, 0xc0001a59e0?, {0xbd02c0?, 0xc0001a59e0?, 0x7fdf63974948?})
        /usr/local/go/src/encoding/gob/decode.go:903 +0x45
encoding/gob.(*Decoder).decodeStruct(0xc0001a59e0?, 0xc000164a20, {0xbda6c0?, 0xc0001a59e0?, 0xc00017ea18?})
        /usr/local/go/src/encoding/gob/decode.go:494 +0x18b
encoding/gob.(*Decoder).decOpFor.func4(0xb67980?, 0xc00017ea18?, {0xbda6c0?, 0xc0001a59e0?, 0x7fdf63808328?})
        /usr/local/go/src/encoding/gob/decode.go:899 +0x2e
encoding/gob.(*Decoder).decodeStruct(0xc00017ea00?, 0xc0001649a0, {0xbf9f80?, 0xc00017ea00?, 0xc00017e780?})
        /usr/local/go/src/encoding/gob/decode.go:494 +0x18b
encoding/gob.(*Decoder).decOpFor.func4(0xb75780?, 0xc00017e780?, {0xbf9f80?, 0xc00017ea00?, 0x7fdf63808328?})
        /usr/local/go/src/encoding/gob/decode.go:899 +0x2e
encoding/gob.(*Decoder).decodeStruct(0xc00017e780?, 0xc000164980, {0xbea6a0?, 0xc00017e780?, 0xc000206670?})
        /usr/local/go/src/encoding/gob/decode.go:494 +0x18b
encoding/gob.(*Decoder).decOpFor.func4(0xb75800?, 0xc000206670?, {0xbea6a0?, 0xc00017e780?, 0xc3ad09?})
        /usr/local/go/src/encoding/gob/decode.go:899 +0x2e
encoding/gob.(*Decoder).decodeStruct(0xb594c0?, 0xc000164940, {0xba8320?, 0xc000206670?, 0xd38560?})
        /usr/local/go/src/encoding/gob/decode.go:494 +0x18b
encoding/gob.(*Decoder).decodeValue(0xc000186180, 0x451200?, {0xb06b80?, 0xc0002060c8?, 0xc002d69101?})
        /usr/local/go/src/encoding/gob/decode.go:1249 +0x24e
encoding/gob.(*Decoder).DecodeValue(0xc000186180, {0xb06b80?, 0xc0002060c8?, 0x0?})
        /usr/local/go/src/encoding/gob/decoder.go:229 +0x1b7
encoding/gob.(*Decoder).Decode(0xc000186180, {0xb06b80?, 0xc0002060c8?})
        /usr/local/go/src/encoding/gob/decoder.go:204 +0x165
github.com/nlpodyssey/spago/nn.Load[...]({0xd393c0, 0xc0002060c0})
        /home/acheong/go/pkg/mod/github.com/nlpodyssey/spago@v1.0.2-0.20230425104021-8a128747fb24/nn/gob.go:49 +0x69
github.com/nlpodyssey/spago/nn.LoadFromFile[...]({0xc00016e820, 0x1?})
        /home/acheong/go/pkg/mod/github.com/nlpodyssey/spago@v1.0.2-0.20230425104021-8a128747fb24/nn/gob.go:68 +0xe9
github.com/acheong08/cybertron/pkg/tasks/textencoding/bert.LoadTextEncoding({0xc0049b2080, 0x3c})
        /home/acheong/go/pkg/mod/github.com/acheong08/cybertron@v0.1.3-0.20230526061827-bda4623885f7/pkg/tasks/textencoding/bert/textencoding.go:58 +0x3b9
github.com/acheong08/cybertron/pkg/tasks.loader[...].resolveModelForTextEncoding(0xd49520)
        /home/acheong/go/pkg/mod/github.com/acheong08/cybertron@v0.1.3-0.20230526061827-bda4623885f7/pkg/tasks/loader.go:213 +0xf1
github.com/acheong08/cybertron/pkg/tasks.loader[...].load(0xd49520)
        /home/acheong/go/pkg/mod/github.com/acheong08/cybertron@v0.1.3-0.20230526061827-bda4623885f7/pkg/tasks/loader.go:95 +0x183
github.com/acheong08/cybertron/pkg/tasks.Load[...](...)
        /home/acheong/go/pkg/mod/github.com/acheong08/cybertron@v0.1.3-0.20230526061827-bda4623885f7/pkg/tasks/loader.go:44
github.com/acheong08/vectordb/vectors.Encode({0xc34d8c, 0x5})
        /home/acheong/Projects/AI/semantic-search-go/vectors/vectors.go:34 +0x1b9
github.com/acheong08/vectordb/rank_test.TestResults(0xc0000a6820)
        /home/acheong/Projects/AI/semantic-search-go/rank/rank_test.go:71 +0x45
testing.tRunner(0xc0000a6820, 0xc81bb0)
        /usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1629 +0x3ea
FAIL    github.com/acheong08/vectordb/rank      0.942s
=== RUN   TestEncoding
--- FAIL: TestEncoding (0.03s)
panic: runtime error: makeslice: len out of range [recovered]
        panic: runtime error: makeslice: len out of range [recovered]
        panic: runtime error: makeslice: len out of range [recovered]
        panic: runtime error: makeslice: len out of range [recovered]
        panic: runtime error: makeslice: len out of range [recovered]
        panic: runtime error: makeslice: len out of range

goroutine 7 [running]:
testing.tRunner.func1.2({0xb5e920, 0xd334e0})
        /usr/local/go/src/testing/testing.go:1526 +0x24e
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1529 +0x39f
panic({0xb5e920, 0xd334e0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
encoding/gob.catchError(0xc0000f80f0)
        /usr/local/go/src/encoding/gob/error.go:38 +0x6d
panic({0xb5e920, 0xd334e0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
encoding/gob.catchError(0xc0000f80f0)
        /usr/local/go/src/encoding/gob/error.go:38 +0x6d
panic({0xb5e920, 0xd334e0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
encoding/gob.catchError(0xc0000f8170)
        /usr/local/go/src/encoding/gob/error.go:38 +0x6d
panic({0xb5e920, 0xd334e0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
encoding/gob.catchError(0xc0000f8170)
        /usr/local/go/src/encoding/gob/error.go:38 +0x6d
panic({0xb5e920, 0xd334e0})
        /usr/local/go/src/runtime/panic.go:884 +0x213
github.com/nlpodyssey/spago/mat.(*Dense[...]).unmarshalBinaryFloat32(0xd4ae00, {0xc00003c709, 0x611, 0x614})
        /home/acheong/go/pkg/mod/github.com/nlpodyssey/spago@v1.0.2-0.20230425104021-8a128747fb24/mat/dense_marshaling.go:91 +0xee
github.com/nlpodyssey/spago/mat.(*Dense[...]).UnmarshalBinary(0xd4ae00?, {0xc00003c709, 0xc2f660?, 0xc00006ec00?})
        /home/acheong/go/pkg/mod/github.com/nlpodyssey/spago@v1.0.2-0.20230425104021-8a128747fb24/mat/dense_marshaling.go:41 +0x53
encoding/gob.(*Decoder).decodeGobDecoder(0xbf2720?, 0xc000049180, 0xc00008adc0, {0xc2f660?, 0xc0001840f0?, 0xc0005fa808?})
        /usr/local/go/src/encoding/gob/decode.go:775 +0x1b6
encoding/gob.(*Decoder).gobDecodeOpFor.func1(0xb?, 0xc00008adc0?, {0xbf2720?, 0xc0001840f0?, 0x196?})
        /usr/local/go/src/encoding/gob/decode.go:1004 +0xc5
encoding/gob.(*Decoder).decodeSingle(0xc2f660?, 0xc00008ae80, {0xbf2720?, 0xc0001840f0?, 0x7fbce84a9248?})
        /usr/local/go/src/encoding/gob/decode.go:461 +0x19b
encoding/gob.(*Decoder).decodeValue(0xc0000f8100, 0xc2f660?, {0xc2f660?, 0xc000015228?, 0x0?})
        /usr/local/go/src/encoding/gob/decode.go:1251 +0x277
encoding/gob.(*Decoder).decodeInterface(0xc0000f8100, {0xd45328?, 0xc24c00}, 0xc00008ada0, {0xc24c00?, 0xc0001831a0?, 0xc0005fac58?})
        /usr/local/go/src/encoding/gob/decode.go:718 +0x265
encoding/gob.(*Decoder).decOpFor.func5(0xb947a0?, 0xc0001831a0?, {0xc24c00?, 0xc0001831a0?, 0x0?})
        /usr/local/go/src/encoding/gob/decode.go:903 +0x45
encoding/gob.(*Decoder).decodeStruct(0xb56000?, 0xc00008ae20, {0xb947a0?, 0xc0001831a0?, 0xd349a0?})
        /usr/local/go/src/encoding/gob/decode.go:494 +0x18b
encoding/gob.(*Decoder).decodeValue(0xc0000f8100, 0x451200?, {0xb0b400?, 0xc0001831a0?, 0xffffffffffffffff?})
        /usr/local/go/src/encoding/gob/decode.go:1249 +0x24e
encoding/gob.(*Decoder).DecodeValue(0xc0000f8100, {0xb0b400?, 0xc0001831a0?, 0xc0000d9860?})
        /usr/local/go/src/encoding/gob/decoder.go:229 +0x1b7
encoding/gob.(*Decoder).Decode(0xc0000f8100, {0xb0b400?, 0xc0001831a0?})
        /usr/local/go/src/encoding/gob/decoder.go:204 +0x165
github.com/nlpodyssey/spago/nn.(*BaseParam).UnmarshalBinary(0xc0001840a0, {0xc0009ee009, 0x6bc, 0x4891da})
        /home/acheong/go/pkg/mod/github.com/nlpodyssey/spago@v1.0.2-0.20230425104021-8a128747fb24/nn/baseparam_marshaling.go:46 +0xbf
encoding/gob.(*Decoder).decodeGobDecoder(0xc2e800?, 0xc000049200, 0xc00008abc0, {0xc2ef20?, 0xc0001840a0?, 0xc0005fb018?})
        /usr/local/go/src/encoding/gob/decode.go:775 +0x1b6
encoding/gob.(*Decoder).gobDecodeOpFor.func1(0xb?, 0xc00008abc0?, {0xc2e800?, 0xc0001840a0?, 0x196?})
        /usr/local/go/src/encoding/gob/decode.go:1004 +0xc5
encoding/gob.(*Decoder).decodeSingle(0xc2ef20?, 0xc00008ac60, {0xc2e800?, 0xc0001840a0?, 0x7fbce84a9248?})
        /usr/local/go/src/encoding/gob/decode.go:461 +0x19b
encoding/gob.(*Decoder).decodeValue(0xc0000f8080, 0xc2ef20?, {0xc2ef20?, 0xc0000150d0?, 0xc00022f6c0?})
        /usr/local/go/src/encoding/gob/decode.go:1251 +0x277
encoding/gob.(*Decoder).decodeInterface(0xc0000f8080, {0xd45328?, 0xbccc60}, 0xc00008aba0, {0xbccc60?, 0xc000105800?, 0xc0005fb3f0?})
        /usr/local/go/src/encoding/gob/decode.go:718 +0x265
encoding/gob.(*Decoder).decOpFor.func5(0xbd7080?, 0xc000105800?, {0xbccc60?, 0xc000105800?, 0x7fbce84aa8c8?})
        /usr/local/go/src/encoding/gob/decode.go:903 +0x45
encoding/gob.(*Decoder).decodeStruct(0xc000105800?, 0xc00008a9c0, {0xbd7080?, 0xc000105800?, 0xc0000ee518?})
        /usr/local/go/src/encoding/gob/decode.go:494 +0x18b
encoding/gob.(*Decoder).decOpFor.func4(0xb64520?, 0xc0000ee518?, {0xbd7080?, 0xc000105800?, 0x7fbce84aaf08?})
        /usr/local/go/src/encoding/gob/decode.go:899 +0x2e
encoding/gob.(*Decoder).decodeStruct(0xc0000ee500?, 0xc00008a920, {0xbf6740?, 0xc0000ee500?, 0xc0000ee3c0?})
        /usr/local/go/src/encoding/gob/decode.go:494 +0x18b
encoding/gob.(*Decoder).decOpFor.func4(0xb72380?, 0xc0000ee3c0?, {0xbf6740?, 0xc0000ee500?, 0x7fbce84aaf08?})
        /usr/local/go/src/encoding/gob/decode.go:899 +0x2e
encoding/gob.(*Decoder).decodeStruct(0xc0000ee3c0?, 0xc00008a900, {0xbe6f80?, 0xc0000ee3c0?, 0xc0000150a8?})
        /usr/local/go/src/encoding/gob/decode.go:494 +0x18b
encoding/gob.(*Decoder).decOpFor.func4(0xb72400?, 0xc0000150a8?, {0xbe6f80?, 0xc0000ee3c0?, 0xc3749a?})
        /usr/local/go/src/encoding/gob/decode.go:899 +0x2e
encoding/gob.(*Decoder).decodeStruct(0xb56000?, 0xc00008a8a0, {0xba4cc0?, 0xc0000150a8?, 0xd349a0?})
        /usr/local/go/src/encoding/gob/decode.go:494 +0x18b
encoding/gob.(*Decoder).decodeValue(0xc0000f8080, 0x451200?, {0xb039c0?, 0xc000014580?, 0xc000180101?})
        /usr/local/go/src/encoding/gob/decode.go:1249 +0x24e
encoding/gob.(*Decoder).DecodeValue(0xc0000f8080, {0xb039c0?, 0xc000014580?, 0x0?})
        /usr/local/go/src/encoding/gob/decoder.go:229 +0x1b7
encoding/gob.(*Decoder).Decode(0xc0000f8080, {0xb039c0?, 0xc000014580?})
        /usr/local/go/src/encoding/gob/decoder.go:204 +0x165
github.com/nlpodyssey/spago/nn.Load[...]({0xd35800, 0xc000014558})
        /home/acheong/go/pkg/mod/github.com/nlpodyssey/spago@v1.0.2-0.20230425104021-8a128747fb24/nn/gob.go:49 +0x69
github.com/nlpodyssey/spago/nn.LoadFromFile[...]({0xc000034280, 0x1?})
        /home/acheong/go/pkg/mod/github.com/nlpodyssey/spago@v1.0.2-0.20230425104021-8a128747fb24/nn/gob.go:68 +0xe9
github.com/acheong08/cybertron/pkg/tasks/textencoding/bert.LoadTextEncoding({0xc00002cb40, 0x3c})
        /home/acheong/go/pkg/mod/github.com/acheong08/cybertron@v0.1.3-0.20230526061827-bda4623885f7/pkg/tasks/textencoding/bert/textencoding.go:58 +0x3b9
github.com/acheong08/cybertron/pkg/tasks.loader[...].resolveModelForTextEncoding(0xd458a0)
        /home/acheong/go/pkg/mod/github.com/acheong08/cybertron@v0.1.3-0.20230526061827-bda4623885f7/pkg/tasks/loader.go:213 +0xf1
github.com/acheong08/cybertron/pkg/tasks.loader[...].load(0xd458a0)
        /home/acheong/go/pkg/mod/github.com/acheong08/cybertron@v0.1.3-0.20230526061827-bda4623885f7/pkg/tasks/loader.go:95 +0x183
github.com/acheong08/cybertron/pkg/tasks.Load[...](...)
        /home/acheong/go/pkg/mod/github.com/acheong08/cybertron@v0.1.3-0.20230526061827-bda4623885f7/pkg/tasks/loader.go:44
github.com/acheong08/vectordb/vectors.Encode({0xd2e400, 0x1})
        /home/acheong/Projects/AI/semantic-search-go/vectors/vectors.go:34 +0x1b9
github.com/acheong08/vectordb/vectors_test.TestEncoding(0xc0000d96c0)
        /home/acheong/Projects/AI/semantic-search-go/vectors/vectors_test.go:13 +0x3f
testing.tRunner(0xc0000d96c0, 0xc7e2d0)
        /usr/local/go/src/testing/testing.go:1576 +0x10b
created by testing.(*T).Run
```

**Comment by acheong08** [comment]
Deleting models and downloading them again fixed it
